name: Test CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-cli:
    name: Test CLI Functionality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build CLI
        run: pnpm run build

      - name: Test CLI help command
        run: |
          echo "Testing CLI help command..."
          node dist/cli/index.js --help
          echo "✅ CLI help command works!"

      - name: Test CLI with invalid arguments
        run: |
          echo "Testing CLI with invalid template..."
          node dist/cli/index.js test-project --template invalid-template --yes --no-install --no-git || echo "✅ Invalid template error handled correctly"

      - name: Test CLI with invalid package manager
        run: |
          echo "Testing CLI with invalid package manager..."
          node dist/cli/index.js test-project --package-manager invalid-pm --yes --no-install --no-git || echo "✅ Invalid package manager error handled correctly"

      - name: Test CLI conflicting flags
        run: |
          echo "Testing CLI with conflicting flags..."
          node dist/cli/index.js test-project --install --no-install --yes --no-git || echo "✅ Conflicting flags error handled correctly"

      - name: Test CLI without project name in yes mode
        run: |
          echo "Testing CLI without project name in yes mode..."
          node dist/cli/index.js --yes --no-install --no-git || echo "✅ Missing project name error handled correctly"

      - name: Test CLI version
        run: |
          echo "Testing CLI version..."
          node dist/cli/index.js --version || echo "Version command not available"
          echo "✅ CLI version check completed!"

      - name: Test CLI with valid arguments (dry run)
        run: |
          echo "Testing CLI with valid arguments..."
          node dist/cli/index.js test-project --template default --yes --no-install --no-git || echo "✅ CLI execution test completed"
